// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type DefaultpagetypeDocumentDataSlicesSlice = never;

/**
 * Content for defaultPageType documents
 */
interface DefaultpagetypeDocumentData {
  /**
   * Slice Zone field in *defaultPageType*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: defaultpagetype.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DefaultpagetypeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *defaultPageType*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: defaultpagetype.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *defaultPageType*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: defaultpagetype.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *defaultPageType*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: defaultpagetype.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * defaultPageType document from Prismic
 *
 * - **API ID**: `defaultpagetype`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DefaultpagetypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DefaultpagetypeDocumentData>,
    "defaultpagetype",
    Lang
  >;

export type AllDocumentTypes = DefaultpagetypeDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DefaultpagetypeDocument,
      DefaultpagetypeDocumentData,
      DefaultpagetypeDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
